
class MoveOutInfo {
  final String petitionNo;
  final String description;
  final String documentNo;
  final String titleDesc;
  final String firstName;
  final String middleName;
  final String lastName;
  final String rcodeCode;
  final String rcodeDesc;
  final String terminateDate;
  final String houseNo;
  final String villageNo;
  final String alleyWayDesc;
  final String alleyDesc;
  final String roadDesc;
  final String subdistrictDesc;
  final String districtDesc;
  final String provinceDesc;
  final String moveDate;
  final String houseID;
  final String oldDateMoveIn;
  final String houseOwner;

  MoveOutInfo(
      {required this.alleyDesc,
      required this.alleyWayDesc,
      required this.description,
      required this.districtDesc,
      required this.documentNo,
      required this.firstName,
      required this.houseID,
      required this.houseNo,
      required this.lastName,
      required this.middleName,
      required this.moveDate,
      required this.oldDateMoveIn,
      required this.petitionNo,
      required this.provinceDesc,
      required this.rcodeCode,
      required this.rcodeDesc,
      required this.roadDesc,
      required this.subdistrictDesc,
      required this.terminateDate,
      required this.titleDesc,
      required this.villageNo,
      required this.houseOwner});
}

List<MoveOutInfo> moveOutList = [
  MoveOutInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายออก',
      districtDesc: 'เมืองตาก',
      documentNo: '0163864335',
      firstName: 'วิทวัส',
      houseID: '63010010991',
      houseNo: '337',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25561019',
      oldDateMoveIn: '25551120',
      petitionNo: '375/2556',
      provinceDesc: 'ตาก',
      rcodeCode: '6386',
      rcodeDesc: 'ท้องถิ่นเทศบาลตำบลไม้งาม',
      roadDesc: '-',
      subdistrictDesc: 'ไม้งาม',
      terminateDate: '0',
      titleDesc: 'นาย',
      villageNo: '6',
      houseOwner: 'จ.ส.อ.นิมิตร เครือหาญชาญพงค์'),
  MoveOutInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายออก',
      districtDesc: 'แม่สอด',
      documentNo: '0863981051',
      firstName: 'วิทวัส',
      houseID: '63980171655',
      houseNo: '5/55',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25551029',
      oldDateMoveIn: '25530610',
      petitionNo: '2055/2555',
      provinceDesc: 'ตาก',
      rcodeCode: '6398',
      rcodeDesc: 'ท้องถิ่นเทศบาลนครแม่สอด',
      roadDesc: 'สองแคว',
      subdistrictDesc: 'แม่สอด',
      terminateDate: '0',
      titleDesc: 'นาย',
      villageNo: '-',
      houseOwner: '-'),
  MoveOutInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายออก',
      districtDesc: 'แม่สอด',
      documentNo: '0763983576',
      firstName: 'วิทวัส',
      houseID: '63980106128',
      houseNo: '4/5',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25530610',
      oldDateMoveIn: '25511216',
      petitionNo: '141/2553',
      provinceDesc: 'ตาก',
      rcodeCode: '6398',
      rcodeDesc: 'ท้องถิ่นเทศบาลนครแม่สอด',
      roadDesc: 'สองแคว',
      subdistrictDesc: 'แม่สอด',
      terminateDate: '0',
      titleDesc: 'ด.ช.',
      villageNo: '-',
      houseOwner: '-'),
  MoveOutInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายออก',
      districtDesc: 'แม่สอด',
      documentNo: '0663981270',
      firstName: 'วิทวัส',
      houseID: '63980106128',
      houseNo: '4/5',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25490405',
      oldDateMoveIn: '0',
      petitionNo: '462/2549',
      provinceDesc: 'ตาก',
      rcodeCode: '6398',
      rcodeDesc: 'ท้องถิ่นเทศบาลนครแม่สอด',
      roadDesc: 'สองแคว',
      subdistrictDesc: 'แม่สอด',
      terminateDate: '25491006',
      titleDesc: 'ด.ช.',
      villageNo: '-',
      houseOwner: '-'),
  MoveOutInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายออก',
      districtDesc: 'แม่สอด',
      documentNo: '0663982655',
      firstName: 'วิทวัส',
      houseID: '63980106128',
      houseNo: '4/5',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25490405',
      oldDateMoveIn: '25410915',
      petitionNo: '1363/2549',
      provinceDesc: 'ตาก',
      rcodeCode: '6398',
      rcodeDesc: 'ท้องถิ่นเทศบาลนครแม่สอด',
      roadDesc: 'สองแคว',
      subdistrictDesc: 'แม่สอด',
      terminateDate: '0',
      titleDesc: 'ด.ช.',
      villageNo: '-',
      houseOwner: '-'),
  MoveOutInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายออก',
      districtDesc: 'แม่สอด',
      documentNo: '0463980130',
      firstName: 'วิทวัส',
      houseID: '63980022838',
      houseNo: '6/1',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25410915',
      oldDateMoveIn: '25310503',
      petitionNo: '40130/642541',
      provinceDesc: 'ตาก',
      rcodeCode: '6398',
      rcodeDesc: 'ท้องถิ่นเทศบาลนครแม่สอด',
      roadDesc: 'บ้านทุ่ง',
      subdistrictDesc: 'แม่สอด',
      terminateDate: '0',
      titleDesc: 'ด.ช.',
      villageNo: '-',
      houseOwner: '-'),
];
