class MoveInInfo {
  final String petitionNo;
  final String description;
  final String documentNo;
  final String titleDesc;
  final String firstName;
  final String middleName;
  final String lastName;
  final String rcodeCode;
  final String rcodeDesc;
  final String terminateDate;
  final String houseNo;
  final String villageNo;
  final String alleyWayDesc;
  final String alleyDesc;
  final String roadDesc;
  final String subdistrictDesc;
  final String districtDesc;
  final String provinceDesc;
  final String moveDate;
  final String houseID;
  final String oldDateMoveIn;
  final String houseOwner;

  MoveInInfo({
    required this.alleyDesc,
    required this.alleyWayDesc,
    required this.description,
    required this.districtDesc,
    required this.documentNo,
    required this.firstName,
    required this.houseID,
    required this.houseNo,
    required this.lastName,
    required this.middleName,
    required this.moveDate,
    required this.oldDateMoveIn,
    required this.petitionNo,
    required this.provinceDesc,
    required this.rcodeCode,
    required this.rcodeDesc,
    required this.roadDesc,
    required this.subdistrictDesc,
    required this.terminateDate,
    required this.titleDesc,
    required this.villageNo,
    required this.houseOwner
  });
}

List<MoveInInfo> moveInList = [
  MoveInInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายเข้า',
      districtDesc: 'พระสมุทรเจดีย์',
      documentNo: '1411059364',
      firstName: 'วิทวัส',
      houseID: '11050497368',
      houseNo: '665/50',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25620523',
      oldDateMoveIn: '25561108',
      petitionNo: '6401/2562',
      provinceDesc: 'สมุทรปราการ',
      rcodeCode: '1105',
      rcodeDesc: 'อำเภอพระสมุทรเจดีย์',
      roadDesc: '-',
      subdistrictDesc: 'บ้านคลองสวน',
      terminateDate: '0',
      titleDesc: 'นาย',
      villageNo: '2',
  houseOwner: '-'),
  MoveInInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายเข้า',
      districtDesc: 'แม่สอด',
      documentNo: '0163864335',
      firstName: 'วิทวัส',
      houseID: '63980171655',
      houseNo: '5/55',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25561108',
      oldDateMoveIn: '25551120',
      petitionNo: '1065/2556',
      provinceDesc: 'ตาก',
      rcodeCode: '6398',
      rcodeDesc: 'ท้องถิ่นเทศบาลนครแม่สอด',
      roadDesc: 'สองแคว',
      subdistrictDesc: 'แม่สอด',
      terminateDate: '0',
      titleDesc: 'นาย',
      villageNo: '-',
  houseOwner: 'นายเล็ก กันยารอง'),
  MoveInInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายเข้า',
      districtDesc: 'เมืองตาก',
      documentNo: '0863981051',
      firstName: 'วิทวัส',
      houseID: '63010010991',
      houseNo: '337',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25551120',
      oldDateMoveIn: '25530610',
      petitionNo: '888/2555',
      provinceDesc: 'ตาก',
      rcodeCode: '6386',
      rcodeDesc: 'ท้องถิ่นเทศบาลตำบลไม้งาม',
      roadDesc: '-',
      subdistrictDesc: 'ไม้งาม',
      terminateDate: '0',
      titleDesc: 'นาย',
      villageNo: '6',
  houseOwner: 'จ.ส.อ.นิมิตร เครือหาญชาญพงค์'),
  MoveInInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายเข้า',
      districtDesc: 'แม่สอด',
      documentNo: '0763983576',
      firstName: 'วิทวัส',
      houseID: '63980171655',
      houseNo: '5/55',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25530610',
      oldDateMoveIn: '25511216',
      petitionNo: '141/2553',
      provinceDesc: 'ตาก',
      rcodeCode: '6398',
      rcodeDesc: 'ท้องถิ่นเทศบาลนครแม่สอด',
      roadDesc: 'สองแคว',
      subdistrictDesc: 'แม่สอด',
      terminateDate: '0',
      titleDesc: 'ด.ช.',
      villageNo: '-',
  houseOwner: 'นายเล็ก กันยารอง'),
  MoveInInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายเข้า',
      districtDesc: 'แม่สอด',
      documentNo: '0663988934',
      firstName: 'วิทวัส',
      houseID: '63980106128',
      houseNo: '4/5',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25511216',
      oldDateMoveIn: '25491108',
      petitionNo: '1085/2551',
      provinceDesc: 'ตาก',
      rcodeCode: '6398',
      rcodeDesc: 'ท้องถิ่นเทศบาลนครแม่สอด',
      roadDesc: 'สองแคว',
      subdistrictDesc: 'แม่สอด',
      terminateDate: '0',
      titleDesc: 'ด.ช.',
      villageNo: '-',
  houseOwner: 'นายเล็ก กันยารอง'),
  MoveInInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายเข้า',
      districtDesc: 'เมืองพิษณุโลก',
      documentNo: '0663982655',
      firstName: 'วิทวัส',
      houseID: '65010783517',
      houseNo: '99/7',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25491108',
      oldDateMoveIn: '25410915',
      petitionNo: '21679/2549',
      provinceDesc: 'พิษณุโลก',
      rcodeCode: '6501',
      rcodeDesc: 'อำเภอเมืองพิษณุโลก',
      roadDesc: '-',
      subdistrictDesc: 'ท่าโพธิ์',
      terminateDate: '0',
      titleDesc: 'ด.ช.',
      villageNo: '9',
  houseOwner: 'นายชินวัฒน์ สิงหะ'),
  MoveInInfo(
      alleyDesc: '-',
      alleyWayDesc: '-',
      description: 'ย้ายเข้า',
      districtDesc: 'แม่สอด',
      documentNo: '0463980130',
      firstName: 'วิทวัส',
      houseID: '63980106128',
      houseNo: '4/5',
      lastName: 'ใจดี',
      middleName: '',
      moveDate: '25410915',
      oldDateMoveIn: '25310503',
      petitionNo: '300401/92541',
      provinceDesc: 'ตาก',
      rcodeCode: '6398',
      rcodeDesc: 'ท้องถิ่นเทศบาลนครแม่สอด',
      roadDesc: 'สองแคว',
      subdistrictDesc: 'แม่สอด',
      terminateDate: '0',
      titleDesc: 'ด.ช.',
      villageNo: '-',
      houseOwner: 'เล็ก กันยารอง'),
];
